spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mk115_spring
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener.simple:
      acknowledge-mode: manual
      concurrency: 5
#      max-concurrency: 5
#      retry.enabled: true

my-username: ali



#springdoc:
#  api-docs:
#    enabled: true